src/CarWash.WebApp.MVC/Models/Lavagen.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace CarWash.WebApp.MVC.Models
{
    public partial class Lavagen
    {
        public string Cpf { get; set; }
        public string Placa { get; set; }
        public DateTime DataLavagem { get; set; }
        public int CodTipoLavagem { get; set; }
        public decimal Valor { get; set; }

        public virtual TipoLavagem CodTipoLavagemNavigation { get; set; }
        public virtual Funcionario CpfNavigation { get; set; }
        public virtual Veiculo PlacaNavigation { get; set; }
    }
}

src/CarWash.WebApp.MVC/Controllers/LavagensController.cs
using CarWash.WebApp.MVC.Models;
using CarWash.WebApp.MVC.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace CarWash.WebApp.MVC.Controllers
{
    public class LavagensController : Controller
    {
        private readonly carwashContext _context;

        public LavagensController(carwashContext context)
        {
            _context = context;
        }

        // GET: Lavagens
        public async Task<IActionResult> Index()
        {
            var carwashContext = _context.Lavagens.Include(l => l.CodTipoLavagemNavigation).Include(l => l.CpfNavigation).Include(l => l.PlacaNavigation);
            var dados = await carwashContext.ToListAsync();

            var totalArrecadado = dados.Sum(d => d.Valor);

            ViewData["Cpf"] = new SelectList(_context.Funcionarios, "Cpf", "Cpf");

            return View(new RelatorioViewModel { Lavagens = dados, TotalArrecadado = totalArrecadado });
        }

        [HttpPost]
        public async Task<IActionResult> ObterRelatorio(DateTime dataLavagem, string cpfFuncionario)
        {
            var carwashContext = _context.Lavagens.Include(l => l.CodTipoLavagemNavigation).Include(l => l.CpfNavigation).Include(l => l.PlacaNavigation);

            var dados = await carwashContext.Where(c => (!new DateTime().Equals(dataLavagem) && c.DataLavagem.Equals(dataLavagem))
                                                         || (!string.IsNullOrEmpty(cpfFuncionario) && c.Cpf.Equals(cpfFuncionario))).ToListAsync();

            if (new DateTime().Equals(dataLavagem) && string.IsNullOrEmpty(cpfFuncionario))
                dados = await carwashContext.ToListAsync();

            var totalArrecadado = dados.Sum(d => d.Valor);

            ViewData["Cpf"] = new SelectList(_context.Funcionarios, "Cpf", "Cpf");

            return PartialView("ObterRelatorio", new RelatorioViewModel { Lavagens = dados, TotalArrecadado = totalArrecadado });
        }

        // GET: Lavagens/Details/5
        public async Task<IActionResult> Details(string cpf, string placa, DateTime dataLavagem)
        {

            var lavagen = await _context.Lavagens
                .Include(l => l.CodTipoLavagemNavigation)
                .Include(l => l.CpfNavigation)
                .Include(l => l.PlacaNavigation)
                .FirstOrDefaultAsync(p => p.Cpf.Equals(cpf) && p.Placa.Equals(placa) && p.DataLavagem.Equals(dataLavagem));

            if (lavagen == null)
            {
                return NotFound();
            }

            return View(lavagen);
        }

        // GET: Lavagens/Create
        public IActionResult Create()
        {
            ViewData["CodTipoLavagem"] = new SelectList(_context.TipoLavagems, "Codigo", "NomeLavagem");
            ViewData["Cpf"] = new SelectList(_context.Funcionarios, "Cpf", "Cpf");
            ViewData["Placa"] = new SelectList(_context.Veiculos, "Placa", "Placa");
            return View();
        }

        // POST: Lavagens/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Cpf,Placa,DataLavagem,CodTipoLavagem,Valor")] Lavagen lavagen)
        {
            if (ModelState.IsValid)
            {
                _context.Add(lavagen);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CodTipoLavagem"] = new SelectList(_context.TipoLavagems, "Codigo", "NomeLavagem", lavagen.CodTipoLavagem);
            ViewData["Cpf"] = new SelectList(_context.Funcionarios, "Cpf", "Cpf", lavagen.Cpf);
            ViewData["Placa"] = new SelectList(_context.Veiculos, "Placa", "Placa", lavagen.Placa);
            return View(lavagen);
        }

        // GET: Lavagens/Edit/5
        public async Task<IActionResult> Edit(string cpf, string placa, DateTime dataLavagem)
        {

            var lavagen = await _context.Lavagens.Where(p => p.Cpf.Equals(cpf) && p.Placa.Equals(placa) && p.DataLavagem.Equals(dataLavagem)).FirstAsync();

            if (lavagen == null)
            {
                return NotFound();
            }

            ViewData["CodTipoLavagem"] = new SelectList(_context.TipoLavagems, "Codigo", "NomeLavagem", lavagen.CodTipoLavagem);
            ViewData["Cpf"] = new SelectList(_context.Funcionarios, "Cpf", "Cpf", lavagen.Cpf);
            ViewData["Placa"] = new SelectList(_context.Veiculos, "Placa", "Placa", lavagen.Placa);

            return View(lavagen);
        }

        // POST: Lavagens/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Cpf,Placa,DataLavagem,CodTipoLavagem,Valor")] Lavagen lavagen)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(lavagen);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LavagenExists(lavagen.Cpf))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            ViewData["CodTipoLavagem"] = new SelectList(_context.TipoLavagems, "Codigo", "NomeLavagem", lavagen.CodTipoLavagem);
            ViewData["Cpf"] = new SelectList(_context.Funcionarios, "Cpf", "Cpf", lavagen.Cpf);
            ViewData["Placa"] = new SelectList(_context.Veiculos, "Placa", "Placa", lavagen.Placa);

            return View(lavagen);
        }

        // GET: Lavagens/Delete/5
        public async Task<IActionResult> Delete(string cpf, string placa, DateTime dataLavagem)
        {
            var lavagen = await _context.Lavagens
                .Include(l => l.CodTipoLavagemNavigation)
                .Include(l => l.CpfNavigation)
                .Include(l => l.PlacaNavigation)
                .FirstOrDefaultAsync(p => p.Cpf.Equals(cpf) && p.Placa.Equals(placa) && p.DataLavagem.Equals(dataLavagem));

            if (lavagen == null)
            {
                return NotFound();
            }

            return View(lavagen);
        }

        // POST: Lavagens/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var lavagen = await _context.Lavagens.FindAsync(id);
            _context.Lavagens.Remove(lavagen);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LavagenExists(string id)
        {
            return _context.Lavagens.Any(e => e.Cpf == id);
        }
    }
}

src/CarWash.WebApp.MVC/Views/Lavagens/Create.cshtml
@model CarWash.WebApp.MVC.Models.Lavagen

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Lavagen</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Cpf" class="control-label"></label>
                <select asp-for="Cpf" class ="form-control" asp-items="ViewBag.Cpf"></select>
            </div>
            <div class="form-group">
                <label asp-for="Placa" class="control-label"></label>
                <select asp-for="Placa" class ="form-control" asp-items="ViewBag.Placa"></select>
            </div>
            <div class="form-group">
                <label asp-for="DataLavagem" class="control-label"></label>
                <input asp-for="DataLavagem" class="form-control" />
                <span asp-validation-for="DataLavagem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CodTipoLavagem" class="control-label"></label>
                <select asp-for="CodTipoLavagem" class ="form-control" asp-items="ViewBag.CodTipoLavagem"></select>
            </div>
            <div class="form-group">
                <label asp-for="Valor" class="control-label"></label>
                <input asp-for="Valor" class="form-control" />
                <span asp-validation-for="Valor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/CarWash.WebApp.MVC/Views/Lavagens/Delete.cshtml
@model CarWash.WebApp.MVC.Models.Lavagen

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Lavagen</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Valor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Valor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CodTipoLavagemNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CodTipoLavagemNavigation.NomeLavagem)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CpfNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CpfNavigation.Cpf)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlacaNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlacaNavigation.Placa)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Cpf" />
        <input type="hidden" asp-for="Placa" />
        <input type="hidden" asp-for="DataLavagem" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

src/CarWash.WebApp.MVC/Views/Lavagens/Details.cshtml
@model CarWash.WebApp.MVC.Models.Lavagen

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Lavagen</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Valor)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Valor)
        </dd>
        <dt class="col-sm-2">
            Tipo Lavagem:
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CodTipoLavagemNavigation.NomeLavagem)
        </dd>
        <dt class="col-sm-2">
            Cpf Funcionário:
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CpfNavigation.Cpf)
        </dd>
        <dt class="col-sm-2">
            Placa:
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PlacaNavigation.Placa)
        </dd>
        <dt class="col-sm-2">
            Data Lavagem:
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DataLavagem)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

src/CarWash.WebApp.MVC/Views/Lavagens/Edit.cshtml
@model CarWash.WebApp.MVC.Models.Lavagen

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Lavagen</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Cpf" />
            <input type="hidden" asp-for="Placa" />
            <input type="hidden" asp-for="DataLavagem" />
            <div class="form-group">
                <label asp-for="CodTipoLavagem" class="control-label"></label>
                <select asp-for="CodTipoLavagem" class="form-control" asp-items="ViewBag.CodTipoLavagem"></select>
                <span asp-validation-for="CodTipoLavagem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Valor" class="control-label"></label>
                <input asp-for="Valor" class="form-control" />
                <span asp-validation-for="Valor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/CarWash.WebApp.MVC/Views/Lavagens/Index.cshtml
@using CarWash.WebApp.MVC.ViewModels
@model RelatorioViewModel

@{
}

<form id="formReport" submit="">
    <div class="form-group">
        <label for="dataLavagem"><b>Data Lavagem</b></label>
        <input name="dataLavagem" type="datetime-local" class="form-control" id="dataLavagem" placeholder="Data Lavagem">
    </div>

    <div class="form-group">
        <label for="cpfFuncionario" class="control-label"><b>CPF Funcionário</b></label>
        <select name="cpfFuncionario" id="cpfFuncionario" class="form-control" asp-items="ViewBag.Cpf">
            <option selected value="">--- SELECIONE ---</option>
        </select>
    </div>

    <button type="submit" class="btn btn-primary">Filtrar</button>
</form>

<div id="divReport" class="mt-3">
    @Html.Partial("ObterRelatorio", Model)
</div>

@section Scripts{
<script>
        $("#formReport").submit((e) => {
        e.preventDefault();

        const dataLavagem = $("#dataLavagem").val();
        const cpfFuncionario = $("#cpfFuncionario").val();

        console.log($("#cpfFuncionario"));

        const data = {
            dataLavagem: dataLavagem,
            cpfFuncionario: cpfFuncionario
        };

        $.post("@Url.Action("ObterRelatorio", "Lavagens")", data, (response) => {
            console.log(response);
            $("#divReport").html(response);
        });
    });
</script>
}

src/CarWash.WebApp.MVC/Views/Lavagens/ObterRelatorio.cshtml
@model CarWash.WebApp.MVC.ViewModels.RelatorioViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Valor
            </th>
            <th>
                Tipo Lavagem
            </th>
            <th>
                Cpf
            </th>
            <th>
                Placa
            </th>
            <th>
                Data
            </th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model.Lavagens)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Valor)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CodTipoLavagemNavigation.NomeLavagem)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CpfNavigation.Cpf)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PlacaNavigation.Placa)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataLavagem)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new {  cpf = item.Cpf, placa = item.Placa, dataLavagem = item.DataLavagem  }) |
                    @Html.ActionLink("Details", "Details", new { cpf = item.Cpf, placa = item.Placa, dataLavagem = item.DataLavagem }) |
                    @Html.ActionLink("Delete", "Delete", new { cpf = item.Cpf, placa = item.Placa, dataLavagem = item.DataLavagem })
                </td>
            </tr>
        }
    </tbody>
</table>


<div>
    <b>Total Arrecadado:</b> @Model.TotalArrecadado
</div>